### ISSUE TITLE
starter problems

### ISSUE THREAD

**Issue by PaolinoAngeletti** [Ramotion/direct-select-android#10]
![immagine](https://user-images.githubusercontent.com/24671034/54835549-9f361980-4cc2-11e9-93e4-696c20d3b818.png)

**Comment by golovin47** [comment]
Hello, @PaolinoAngeletti. Try running example apps, if they work correctly, then there are issues in your implementation. Also stacktrace, provided by you, isn't full so i can't see the root of the exception. But i think that you just need to move to androidx, because this lib uses androidx.
