### ISSUE TITLE
Does it work with ScrollView?

### ISSUE THREAD

**Issue by melixfueller** [Ramotion/direct-select-android#2]
I have a Scroll View and if the ListView is open, I only can scroll the background and the list is freezing.
Are there any possibilities to fix this?

**Comment by shrikanth7698** [comment]
Did you find any solution ?

**Comment by Qenawi** [comment]
NO Solution So Far ;(

**Comment by golovin47** [comment]
Hello, @melixfueller, @shrikanth7698, @Qenawi. To make direct-select-android work in layout with ScrollView or NestedScrollView, you should use this approach:

    public boolean dispatchTouchEvent(MotionEvent ev) {
        if (countryListView.getVisibility() == View.VISIBLE) { 
            ((ScrollView) (findViewById(R.id.rootScrollView))).requestDisallowInterceptTouchEvent(true);
        }
        if (sportListView.getVisibility() == View.VISIBLE) {
            ((ScrollView) (findViewById(R.id.rootScrollView))).requestDisallowInterceptTouchEvent(true);
        }
        if (countryListView.getVisibility() != View.VISIBLE && sportListView.getVisibility() != View.VISIBLE) {
            ((ScrollView) (findViewById(R.id.rootScrollView))).requestDisallowInterceptTouchEvent(false);
        }

        return super.dispatchTouchEvent(ev);
    }

This method should be overridden in your Activity. Basically what you're doing here is restricting your ScrollView to intercept touch events in case any of your DSListView is visible.
