### ISSUE TITLE
different data_array set programmatically

### ISSUE THREAD

**Issue by VenkataKrsna** [Ramotion/direct-select-android#3]
how can I set different ds:data_array lists in DSListView according to user need. I have eighteen chapters in one DSListView by list and each chapter has a different array list. I want to give the array list to that particular chapter selected by the user.

**Comment by golovin47** [comment]
Hello, @venkat8995. We've added changes to make it possible to correctly change adapter items whenever you need it. All you need to do is call setAdapter() with your new adapter instance on your DSListView object.
